### ISSUE TITLE
Replace couts and cerr with messaget calls

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#450] opened 2021-06-16 14:06 UTC
ESBMC has a lot of calls using `std::cout` and `std::cerr`, we should use the messaget interface which provides more control of the output level and destination

**Comment by mikhailramalho** [comment] 2021-06-16 14:14
Duplicate of https://github.com/esbmc/esbmc/issues/174?

**Comment by rafaelsamenezes** [comment] 2021-06-16 14:26
> Duplicate of #174?

Somewhat, I think that this is the first step to solve that. This issue objective is to isolate cout and cerr calls into a messaget specialization, it shouldn't add fmt.

**Closed as completed** 2021-07-08 12:09 UTC
Labels: good first issue
