### ISSUE TITLE
Successful verification with `--claim`, but failure without

### ISSUE THREAD

**Issue by intrigus-lgtm** [esbmc/esbmc#2109] opened 2024-10-31 01:38 UTC
I'm trying to verify a moderately big c++ program.
When running it normally (i.e. without `--claim`) I get a counter example from let's say claim 72.
When I'm now running esbmc again, but add `--claim 72`, it verifies succesfully.
I find this very weitd.
Am I missing something?

(I can not share the code right now, because I use a pretty custom fork of esbmc and won't have access to the code till next monday.)

**Comment by intrigus-lgtm** [comment] 2024-11-02 16:16
Anybody got an idea whether this is a bug or a mistake on my side?

**Comment by lucasccordeiro** [comment] 2024-11-02 19:27
@intrigus-lgtm: what is the type of property for claim 72 (memory safety, overflow, concurrency, user-specified assertion)?

**Comment by intrigus-lgtm** [comment] 2024-11-02 20:01
It's a user-specified assertion.

**Comment by lucasccordeiro** [comment] 2024-11-04 14:19
> It's a user-specified assertion.

You have found a bug in ESBMC. If you could send us a reduced version of the program, that would allow us to inspect the ESBMC source code and identify the root cause of this issue.

Does this issue also happen with the option `--multi-property`?

**Comment by intrigus-lgtm** [comment] 2024-11-06 19:06
~~Okay the boring resolution of my problem is that `--show-claims` is one-based, while `--claim` expects the index to be zero-based...~~
EDIT: That's was actually only a coincidence. The actual problem is described in https://github.com/esbmc/esbmc/pull/2121.

@lucasccordeiro any objections to change `--show-claims` to be zero-based as well?
I'd say that this should break the least code hopefully.

**Comment by lucasccordeiro** [comment] 2024-11-06 19:46
> any objections to change --show-claims to be zero-based as well?

@intrigus-lgtm: No objections at all ;-)

Can you please submit a PR to fix this issue?

**Comment by intrigus-lgtm** [comment] 2024-11-07 00:25
I submitted https://github.com/esbmc/esbmc/pull/2121 which kind of fixes the issue, although my previous conclusion was wrong.

**Comment by lucasccordeiro** [comment] 2024-11-07 09:01
Closed via https://github.com/esbmc/esbmc/pull/2121.

**Closed as completed by lucasccordeiro** 2024-11-07 09:01 UTC
