### ISSUE TITLE
errors occured when handling cblas

### ISSUE THREAD

**Issue by HymnOfLight** [esbmc/esbmc#1263] opened 2023-08-07 07:24 UTC
I was using ESBMC 7.3.0 latest version, to verify a C source file includes cblas.h. It returns the error below:

ESBMC version 7.3.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
ERROR: Conversion of unsupported clang type: "Complex
ComplexType 0x61744d0 '_Complex double'
`-BuiltinType 0x6173fc0 'double'

ERROR: CONVERSION ERROR

I can compile the file using gcc test_cblas.c -lopenblas -o test_cblas
and run it successfully with the output:
![image](https://github.com/esbmc/esbmc/assets/30403502/de4b4f4a-b6dc-4db9-9281-727f934cd097)

The command I used is: esbmc test_cblas.c
And here is the file test_cblas.c
[test_cblas.zip](https://github.com/esbmc/esbmc/files/12273353/test_cblas.zip)

**Comment by lucasccordeiro** [comment] 2023-08-07 07:43
Currently, we don't support complex numbers in ESBMC; this feature would require some weeks of development to add such support.

**Comment by rafaelsamenezes** [comment] 2023-08-10 09:03
I will mark as duplicate of #1088 and close this.

**Closed as not planned by rafaelsamenezes** 2023-08-10 09:03 UTC
Labels: duplicate
