### ISSUE TITLE
Negative number of assignments during multi thread verification is confusing

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#1387] opened 2023-10-03 18:37 UTC
ESBMC is printing a negative number of assignments:
```
Generated 51 VCC(s), 0 remaining after simplification (-233883 assignments)
BMC program time: 0.001s
Thread interleavings 1145
Symex completed in: 0.002s (212 assignments)
Slicing time: 0.000s (removed 234293 assignments)
Generated 52 VCC(s), 0 remaining after simplification (-234081 assignments)
BMC program time: 0.003s
Thread interleavings 1146
Symex completed in: 0.000s (210 assignments)
Slicing time: 0.001s (removed 234495 assignments)
Generated 53 VCC(s), 0 remaining after simplification (-234285 assignments)
BMC program time: 0.001s
Thread interleavings 1147
Symex completed in: 0.001s (212 assignments)
Slicing time: 0.001s (removed 234699 assignments)
Generated 52 VCC(s), 0 remaining after simplification (-234487 assignments)
BMC program time: 0.002s
Thread interleavings 1148
Symex completed in: 0.001s (210 assignments)
Slicing time: 0.000s (removed 234901 assignments)
```
For comparison, this is esbmc 6.7:
```
Symex completed in: 0.002s (177 assignments)
Slicing time: 0.000s (removed 156 assignments)
Generated 62 VCC(s), 2 remaining after simplification (21 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.0
Encoding to solver time: 0.000s
Runtime decision procedure: 0.000s
BMC program time: 0.002s
```

**Comment by lucasccordeiro** [comment] 2023-10-03 18:59
I noticed this bug some time ago. I asked @Anthonysdu to check it, but he couldn't reproduce this issue on his machine.

Can you specify here the machine/OS/etc you're using?

**Comment by mikhailramalho** [comment] 2023-10-03 19:05
Nothing special: ubuntu and esbmc current master.

**Comment by lucasccordeiro** [comment] 2023-10-03 19:29
Thanks, @mikhailramalho.

I'll ask @Anthonysdu to focus on this issue when he returns from his internship.

**Comment by Anthonysdu** [comment] 2023-10-04 01:07
I met the same issue when updating to master branch at arm.
Before that I was using v6.8 and the number is positive.

**Comment by lucasccordeiro** [comment] 2023-10-17 10:18
Closed via https://github.com/esbmc/esbmc/pull/1395.

**Closed as completed by lucasccordeiro** 2023-10-17 10:18 UTC
