### ISSUE TITLE
[Concurrency] Pthread mutex is not working for main thread

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#548] opened 2021-11-05 21:08 UTC
See the following example:

```c
int glob1 = 0;
pthread_mutex_t mutex2 = PTHREAD_MUTEX_INITIALIZER;

void *t_fun(void *arg) {
  pthread_mutex_lock(&mutex2);
  glob1 = 5;

  pthread_mutex_unlock(&mutex2); 
  pthread_mutex_lock(&mutex2);
  glob1 = 10;

  pthread_mutex_unlock(&mutex2);
  return NULL;
}

// Race condition here
void *foo(void *arg)
{
  pthread_mutex_lock(&mutex2); // wait/block mutex2
  __VERIFIER_assert(glob1 == 0); // 
  pthread_mutex_unlock(&mutex2); // unlock mutex2
}

int main(void) {
  pthread_t id;  
  pthread_create(&id, NULL, t_fun, NULL); //start thread
  *(foo)(0);
  
  pthread_join (id, NULL);
  
  return 0;
}
```

In this example, there is a race condition over the `glob1` var when:

1. Thread `id` starts and locks `mutex2` (at function t_fun)
2. Main thread starts `foo` and should wait for `mutex2`
3. Thread `id` changes the value of `glob1`  to 5 and unlocks `mutex2`
4. Main thread checks for the assertion `glob1 == 0`. Which should fail.

ESBMC can't find this violation. If we, however, add a new thread i.e replace the `main` with:

```c
int main(void) {
  pthread_t id, id2;  
  pthread_create(&id, NULL, t_fun, NULL); //start thread
  pthread_create(&id2, NULL, foo, NULL); //start thread
  
  pthread_join (id, NULL);
  pthread_join (id2, NULL);  
  return 0;
}
```

Then ESBMC is able to find the bug.

**Comment by rafaelsamenezes** [comment] 2021-11-05 21:25
Apparently, forcing the main call to be inside a thread... fixes the issue. Something like:

```
__ESBMC_main:
  ...
  pthread_t __ESBMC_main_thread;
  pthread_create(__ESBMC_main_thread, 0, main, 0);
  pthread_join(__ESBMC_main_thread);
  ...
```

**Comment by fbrausse** [comment] 2021-12-09 17:41
On the first example (adding `#include <pthread.h>`) I get

```
ESBMC version 6.8.0 64-bit x86_64 linux
file gh-548-2.c: Parsing
gh-548-2.c:21:3: warning: implicit declaration of function '__VERIFIER_assert' is invalid in C99 [-Wimplicit-function-declaration]
  __VERIFIER_assert(glob1 == 0); // 
  ^
gh-548-2.c:23:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
gh-548-2.c:28:3: warning: expression result unused [-Wunused-value]
  *(foo)(0);
  ^~~~~~~~~
Converting
Generating GOTO Program
GOTO program creation time: 0.209s
GOTO program processing time: 0.003s
Starting Bounded Model Checking
**** WARNING: no body for function __VERIFIER_assert
Symex completed in: 0.019s (98 assignments)
Slicing time: 0.001s (removed 60 assignments)
Generated 21 VCC(s), 2 remaining after simplification (38 assignments)
No solver specified; defaulting to z3
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.002s
Solving with solver Z3 v4.8.11
Encoding to solver time: 0.002s
Runtime decision procedure: 0.000s
Building error trace

Counterexample:

State 1 file gh-548-2.c line 3 thread 0
----------------------------------------------------
  mutex2 = { byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 2), byte_extract_little_endian(0, 3), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 2), byte_extract_little_endian(0, 3), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 2), byte_extract_little_endian(0, 3), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 2), byte_extract_little_endian(0, 3), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 2), byte_extract_little_endian(0, 3), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 2), byte_extract_little_endian(0, 3), byte_extract_little_endian(0, 4), byte_extract_little_endian(0, 5), byte_extract_little_endian(0, 6), byte_extract_little_endian(0, 7), byte_extract_little_endian(0, 0), byte_extract_little_endian(0, 1), byte_extract_little_endian(0, 2), byte_extract_little_endian(0, 3), byte_extract_little_endian(0, 4), byte_extract_little_endian(0, 5), byte_extract_little_endian(0, 6), byte_extract_little_endian(0, 7) }

State 5 file gh-548-2.c line 28 function main thread 0
----------------------------------------------------
Violated property:
  file gh-548-2.c line 28 function main
  dereference failure: invalid pointer


VERIFICATION FAILED
```

Assuming you meant to call `foo(0)` without dereferencing its missing return value,

> Then ESBMC is able to find the bug.

I can't reproduce this neither with current master (10351abc5ce24d23be7a4dddc8f96e5e4d2bb713), the version from Nov 4th (9316a01d50c8b9461d210a446322bb1cfdaaa8f1) nor [v6.8](https://github.com/esbmc/esbmc/tree/v6.8): both examples give `VERIFICATION SUCCESSFUL`. Any parameters I should be using?

**Comment by lucasccordeiro** [comment] 2022-01-17 15:36
ESBMC does not understand this assignment:

```
pthread_mutex_t mutex2 = PTHREAD_MUTEX_INITIALIZER;
```

If we initialize the mutex as

```
pthread_mutex_init(&mutex2, NULL);
```

ESBMC can find the property violation. So, we have to teach ESBMC the meaning of this assignment:

```
pthread_mutex_t mutex2 = PTHREAD_MUTEX_INITIALIZER;
```

**Comment by lucasccordeiro** [comment] 2022-01-18 21:14
Closed via https://github.com/esbmc/esbmc/pull/599.

**Closed as completed by lucasccordeiro** 2022-01-18 21:14 UTC
