### ISSUE TITLE
How to check for memory leak after calling exit()

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#542] opened 2021-11-02 20:26 UTC
Consider the following program:
```
#include <stdlib.h>

int **g = NULL;

void free_g1() {
  free(g);
  g = NULL;
}

void free_g2() {
  if (g != NULL)
    free(*g);
}

void f() {
  *g = (int *)malloc(sizeof(int));
  atexit(free_g1);
  exit(1);
}

int main() {
  g = (int **)malloc(sizeof(int *));
  atexit(free_g2);
  f();
  return 0;
}
```

When calling `exit(1)` from `f()`, functions `free_g1` and `free_g2` will be called (in that order) to free the memory, but because of `g = NULL` in `free_g1`, the guard `if (g != NULL)` is false and `*g` will not be freed.

The problem with esbmc is because our model of `exit(int)` is:
```
void exit(int status)
{
  __atexit_handler();
  __ESBMC_assume(0);
}
```

which generates the following ssa (with `--memory-leak-check`):
```
...
// 66 file stdlib.c line 38 function exit
/* 81 */ (assume)0

// 137 file global-atexit-2.c line 29 function main (dereference failure: forgotten memory: dynamic_1_value)
/* 82 */ (assert)__ESBMC_deallocated&0#13[POINTER_OBJECT((void *)(&dynamic_1_value))] == 1

// 137 file global-atexit-2.c line 29 function main (dereference failure: forgotten memory: dynamic_2_value)
/* 83 */ (assert)__ESBMC_deallocated&0#13[POINTER_OBJECT((void *)(&dynamic_2_value))] == 1
```

Because of the `assume(0)`, the two assertions are not checked.

A couple of ideas on how to fix it:
1. If it's a memory-leak check, always check it, regardless of any previous guard. This can be done by checking the comment added by the memory leak check `dereference failure: forgotten memory: bla`. It should go here: https://github.com/esbmc/esbmc/blob/master/src/goto-symex/symex_target_equation.cpp#L229 (`assumpt_ast` is the collection of assumptions up to that SSA).
2. add a new intrinsic `__ESBMC_memory_leak_check` which triggers the memory leak check (if the flag is enabled) and change exit model to:
```
void exit(int status)
{
  __atexit_handler();
  __ESBMC_memory_leak_check();
  __ESBMC_assume(0);
}
```
3. Change the assume formula to add memory leak checks if we assume(cond), i.e., the program finishes, so whenever we call `assume(cond)`,  it generates:
```
assert(__ESBMC_deallocated&0#13[POINTER_OBJECT((void *)(&dynamic_1_value))] == 1)
Guards: !cond

assert(__ESBMC_deallocated&0#13[POINTER_OBJECT((void *)(&dynamic_2_value))] == 1)
Guards: !cond

assume(cond)
```

Approach 1 seems more generic and easier to implement but it feels a bit hackish.
Approach 2 requires us to remember all the places it needs to be added.
Approach 3 feels the correct approach IMO, however, we start to report thousands of false results in SV-Comp because of the memory-leak/memory-cleanup mix-up in esbmc: whenever we call an abort, we report memory leak even if all the pointers are still reachable.

**Comment by fbrausse** [comment] 2021-11-03 23:30
Except for the `__atexit_handler()`, the models for `exit` and `abort` seem to be the same (if you don't take into account the difference in the unused
https://github.com/esbmc/esbmc/blob/43d8c5d94a9aac4e981cc9baf68ac20184cba31a/src/cpp/library/cstdlib#L118-L125).
Would it be possible to define the concepts of "normal" and "abnormal" program termination symbolically in esbmc? From my perspective, memory safety for abnormal termination (be it SIGABRT or _Exit) would not be a (default) verification target. To me an additional intrinsic for either of these conditions seems to be the most extendible approach.

**Comment by rafaelsamenezes** [comment] 2021-11-04 12:32
> add a new intrinsic __ESBMC_memory_leak_check which triggers the memory leak check (if the flag is enabled) and change exit model to:

I think that this is the best approach. However, I would prefer if the intrinsic was just a check:

```c
_Bool  __ESBMC_memory_leak_check_enabled // initialize this at esbmc_main

void exit(int status)
{
  __atexit_handler();
  // Stops if memory leak is disabled
  __ESBMC_assume(__ESBMC_memory_leak_check_enabled);
}
```

I think that this would be easier to maintain.

**Comment by mikhailramalho** [comment] 2021-11-18 17:22
> Except for the `__atexit_handler()`, the models for `exit` and `abort` seem to be the same (if you don't take into account the difference in the unused
> 
> https://github.com/esbmc/esbmc/blob/43d8c5d94a9aac4e981cc9baf68ac20184cba31a/src/cpp/library/cstdlib#L118-L125
> 
> ).
> Would it be possible to define the concepts of "normal" and "abnormal" program termination symbolically in esbmc? From my perspective, memory safety for abnormal termination (be it SIGABRT or _Exit) would not be a (default) verification target. To me an additional intrinsic for either of these conditions seems to be the most extendible approach.

There was a lengthy discussion about abornal and normal termination, IIRC abnormal termination was decided to be when the program exits without explicit calls from the program (i.e., null pointer deref), while a normal termination is whenever a program reaches the end of main or exits by calling exit(), abort() or _Exit().



> > add a new intrinsic __ESBMC_memory_leak_check which triggers the memory leak check (if the flag is enabled) and change exit model to:
> 
> I think that this is the best approach. However, I would prefer if the intrinsic was just a check:
> 
> ```c
> _Bool  __ESBMC_memory_leak_check_enabled // initialize this at esbmc_main
> 
> void exit(int status)
> {
>   __atexit_handler();
>   // Stops if memory leak is disabled
>   __ESBMC_assume(__ESBMC_memory_leak_check_enabled);
> }
> ```
> 
> I think that this would be easier to maintain.

The problem here is that we still need to honour an assume(0), even if memory-leak is enabled. Any code after an assume(0) should be unreachable.

**Comment by mikhailramalho** [comment] 2021-11-18 17:30
What if we model an assume(0) as a jump to `__atexit_handler()`? 

Or better still, we could create a new function `__ESBMC_end_main()` (or a better name) which would call `pthread_end_main_hook` and `__atexit_handler` (or others that we might need in the future). 

Then we could have a model for _Exit:
```
_Bool  __ESBMC_call_end_main = 1; // By default always call end_main

void _Exit(int status)
{
  __ESBMC_call_end_main  = 0; // Only case where end_main is not called.
  __ESBMC_assume(0);
}
```

We could  change the smt_conv to always guard the ssa in `__ESBMC_end_main()` with `__ESBMC_call_end_main`.

WDYT?

**Comment by fbrausse** [comment] 2021-12-01 12:59
> There was a lengthy discussion about abornal and normal termination, IIRC [...] a normal termination is whenever a program reaches the end of main or exits by calling exit(), abort() or _Exit().

To be honest, that sounds strange to me, in particular in light of C++ destructors of static variables (and C functions marked with `__attribute__((destructor))`), which are run neither on _Exit() nor abort(), but they are run on exit() and return from main().

**Comment by lucasccordeiro** [comment] 2023-03-13 20:32
Closed via https://github.com/esbmc/esbmc/tree/master/regression/esbmc/github_542_fail.

**Closed as completed by lucasccordeiro** 2023-03-13 20:32 UTC
