### ISSUE TITLE
Infinite loop code gives verification successful 

### ISSUE THREAD

**Issue by Mohannad-Aldughaim** [esbmc/esbmc#150] opened 2020-04-09 15:01 UTC
Hello, 

I found this bug while running a code with infinite loop. Not sure if this is actually a bug or misuse of the the software but it shows that verification is successful. Here is the code with ESBMC output:
```
int main() {
	int i, b[10];
	for (i = 0; i < 10; i++) {
		b[i] = i;
	}
	for (i = 0; i < 10; i) {
		if (b[i] != i) {
		ERROR: return 1;
		}
	}
	return 0;
}
```
The result from ESBMC :
```
$ ./esbmc p1.c --quiet --k-induction
ESBMC version 6.2.0 64-bit x86_64 linux
file p1.c: Parsing
p1.c:7:22: warning: expression result unused [-Wunused-value]
        for (i = 0; i < 10; i) {
                            ^
Converting
Generating GOTO Program
GOTO program creation time: 0.102s
GOTO program processing time: 0.001s

*** Iteration number 1 ***
*** Checking base case
Starting Bounded Model Checking
Symex completed in: 0.000s (13 assignments)
Slicing time: 0.000s (removed 12 assignments)
Generated 2 VCC(s), 0 remaining after simplification (1 assignments)
BMC program time: 0.000s
No bug has been found in the base case
*** Checking forward condition
Starting Bounded Model Checking
Symex completed in: 0.000s (13 assignments)
Slicing time: 0.000s (removed 12 assignments)
Generated 3 VCC(s), 1 remaining after simplification (1 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.0
Encoding to solver time: 0.000s
Runtime decision procedure: 0.000s
The forward condition is unable to prove the property

*** Iteration number 2 ***
*** Checking base case
Starting Bounded Model Checking
Symex completed in: 0.000s (15 assignments)
Slicing time: 0.000s (removed 14 assignments)
Generated 4 VCC(s), 0 remaining after simplification (1 assignments)
BMC program time: 0.000s
No bug has been found in the base case
*** Checking forward condition
Starting Bounded Model Checking
Symex completed in: 0.001s (15 assignments)
Slicing time: 0.000s (removed 14 assignments)
Generated 5 VCC(s), 1 remaining after simplification (1 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.0
Encoding to solver time: 0.000s
Runtime decision procedure: 0.000s
The forward condition is unable to prove the property
*** Checking inductive step
Starting Bounded Model Checking
Symex completed in: 0.001s (31 assignments)
Slicing time: 0.000s (removed 22 assignments)
Generated 4 VCC(s), 2 remaining after simplification (9 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.0
Encoding to solver time: 0.000s
Runtime decision procedure: 0.001s
BMC program time: 0.002s

VERIFICATION SUCCESSFUL

Solution found by the inductive step (k = 2)


```

**Comment by mikhailramalho** [comment] 2020-04-09 15:12
Hi Mohannad, that's indeed the intended behavior: there is no bug in this program. The k-induction is simply stating that there is no path of execution that leads to a property violation (e.g., an assert(0)). The ERROR label is never reachable because `b[i] != i` is always false.

Maybe you're interested in checking if the label ERROR is reachable? You can add the option `--error-label YYY` to esbmc's command line and it'll check if the label `YYY` is reachable from main (in your case YYY = ERROR).

**Comment by lucasccordeiro** [comment] 2020-04-10 14:02
Hello Mohannad,

Even if you run ESBMC in your C code as:

$esbmc file.c --error-label ERROR --k-induction

The label "ERROR" is unreachable since `b[i] != i` is always false, As pointed out by @mikhailramalho; therefore, the ESBMC k-induction approach is providing the correct answer.

For now, I'll close this ticket; if you have further issues, please let us know.

Best,
Lucas

**Closed as completed by lucasccordeiro** 2020-04-10 14:02 UTC

**Comment by lucasccordeiro** [comment] 2020-04-11 10:24
Hello Mohannad,

BTW, if you want to check whether the program terminates or not, then you can call ESBMC as:

$esbmc file.c --termination

Best,
Lucas

**Comment by Mohannad-Aldughaim** [comment] 2020-04-11 17:14
Thank you Lucas and Mikhail. Its is clear to me now.
