### ISSUE TITLE
[C++ verification] Various issues in copy constructor and member expr conversions

### ISSUE THREAD

**Issue by ChenfengWei0** [esbmc/esbmc#961] opened 2023-04-09 18:43 UTC
command: `esbmc 1.cpp`

result:
```sh
$./esbmc 1.cpp
ESBMC version 7.1.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
esbmc: /root/workspace/ESBMC_Commit/esbmc/src/util/migrate.cpp:528: expr2tc sym_name_to_symbol(irep_idt, type2tc): Assertion `endatptr != atstr.c_str()' failed.
[1]    6788 IOT instruction  ./esbmc 1.cpp
```

`1.cpp`
```cpp
class Vehicle
{
public:
  int x;
  Vehicle()
  {
    x = 1;
  }

  int empty()
  {
    return x;
  }
};

int main()
{
  Vehicle xx = Vehicle();
  int y = xx.empty();
  // xx.empty();  this also failed.
  return 0;
}
```
- ESBMC version:  [f180916](https://github.com/esbmc/esbmc/commit/f180916c63dda439a2640b8ced6f35e534cef64a)

---

This might be related to #896. When using test case:
```cpp
class Foo
{
public:
  Foo(){};
  ~Foo(){};
  int Execute() { return 0; };
};

int main()
{
  Foo foo = Foo();
  int x = foo.Execute();
  return 0;
}
```

The result:
```sh
$./esbmc 1.cpp
ESBMC version 7.1.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
ERROR: unexpected function argument: member
[1]    8467 IOT instruction  ./esbmc 1.cpp
```

symbol table:
```
int x=member
  * type: code
      * arguments: 
        0: argument
            * type: pointer
                * subtype: symbol
                    * identifier: tag-Foo
            * #base_name: this
            * #identifier: c:@S@Foo@F@Execute#this
      * return_type: signedbv
          * width: 32
          * #cpp_type: signed_int
      * #inlined: 1
      * #member_name: tag-Foo
      ...
```

**Comment by kunjsong01** [comment] 2023-04-12 21:05
Updated the title as the problems are not caused by calling member functions with return value and ESBMC is able to verify the following test case: 
```cpp
#include <cassert>
class Vehicle
{
public:
  int x;
  Vehicle()
  {
    x = 1;
  }

  int empty()
  {
    return x;
  }
};

int main()
{
  //Vehicle v = Vehicle();
  Vehicle v;
  assert(v.x == 1);
  assert(v.empty() != 1); // FAIL as it should be 1

  return 0;
}
```

**Comment by kunjsong01** [comment] 2023-04-12 21:13
There are two independent issues here: 

**1. Empty name for copy constructor `rhs` parameter**
The first error signature (see below) is caused by empty name for copy constructor parameter. 
```
esbmc: /root/workspace/ESBMC_Commit/esbmc/src/util/migrate.cpp:528: expr2tc sym_name_to_symbol(irep_idt, type2tc): Assertion `endatptr != atstr.c_str()' failed.
```
```
| |-CXXConstructorDecl 0x561988534bc0 <line:3:7> col:7 implicit used Vehicle 'void (const Vehicle &) throw()' inline default trivial
| | |-ParmVarDecl 0x561988534cf0 <col:7> col:7 used 'const Vehicle &'
| | |-CXXCtorInitializer Field 0x5619885346b0 'x' 'int'
| | | `-ImplicitCastExpr 0x56198853e478 <col:7> 'int' <LValueToRValue>
| | |   `-MemberExpr 0x56198853e448 <col:7> 'const int' lvalue .x 0x5619885346b0
| | |     `-DeclRefExpr 0x56198853e428 <col:7> 'const Vehicle' lvalue ParmVar 0x561988534cf0 '' 'const Vehicle &'
```
Clang AST doesn't provide a default name for the const ref `rhs` paremeter. We got: 
```
this->x = ->x;
```

**2. Failed to adjust the member function access in an assign statement**
in statement `int y = xx.empty();`

```
ERROR: unexpected function argument: member
```

**Comment by kunjsong01** [comment] 2023-04-18 09:48
Closed via https://github.com/esbmc/esbmc/pull/968 and https://github.com/esbmc/esbmc/pull/969 
No more actions needed

**Closed as completed by kunjsong01** 2023-04-18 09:48 UTC
Labels: C++
