### ISSUE TITLE
C++ Support

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#198] opened 2020-06-08 18:40 UTC
What remains to be done? Shall we make a set of tasks with a milestone/project?

**Comment by mikhailramalho** [comment] 2020-06-08 22:43
I'm not sure what remains to be done there. The last time I touched that code was 2017.

I do remember having a version where only constructors and virtual-tables were missing, I think I sent it to @feliperodri last year. The code I sent is very old though, and probably won't easily merge to ESBMC.

I guess the first task would be to try to rebase the `clang-c-frontend` branch, then merge it to master. IIRC the code there should already support some minor C++ features.

After we merge it, then we can start to test for missing C++ features. 

Virtual tables should not be a problem to implement, but support constructors will likely require a lot of work, especially because neither goto nor symex understands what a constructor is. The current C++ frontend flattens all the constructors before generating the symbol table, so the easy path would be to do the same in the new frontend.

**Comment by lucasccordeiro** [comment] 2020-06-10 07:40
@mikhailramalho: Could you please confirm that the branch that contains the clang c++ frontend is this one https://github.com/esbmc/esbmc/tree/clang-c-frontend?

@feliperodri: did you manage to make some progress on this C++ frontend?

**Comment by feliperodri** [comment] 2020-06-11 05:49
@rafaelsamenezes I think we should create a set of tasks with a milestone/project. We should break the tasks as small as possible.

@lucasccordeiro I didn't make progress on the C++ frontend.

This is the last detailed information that @mikhailramalho sent me about the C++ frontend.

----------------------------

_E-mail from Mikhail Gadelha (16 Sep 2019)_

Right now, we have two versions of the C++ frontend using clang:

[Version 1](https://drive.google.com/file/d/0B3wN6aAcbpi6SUxWcnpkQjhzR1V1LWVZM0h3ekVfOU9OOHp3/view?usp=sharing).

1. I started the first version about a year ago and it implements the conversion for most of the nodes. There are a few issues though:

* Partial support for polymorphism: we only support cases where casts can be statically determined [0]. There is no code to build the virtual table. Clang does have code to build the vtable but only when building the CFG of the program, so it's a matter of using that or the code that's already on the old C++ frontend.

* Constructors are hacked to work: AFAIK both ESBMC and CBMC handle constructors and destructors like function calls:
```c
foo bar(2, 3);
```
is converted to (similar to method calls):
```c
foo bar;
foo::foo(&bar, 2, 3);
```
And this format is very different from the AST generated by clang. I tried to support most of the cases but the long term solution will probably be to teach the goto conversion (and maybe symex) to understand constructors separately. Things get particularly bad when it comes to temporaries. 

* A number of improvements were not backported to the code, the most important is that now we use clang to generate tag names (replacing the `type2name.cpp` code).

* There are a number of corner cases that need to be implemented, e.g, in member initializer lists, arrays are initialized using undeclared variables (it's pattern matched later by llvm) and there are some cases where a try block can have an empty body.

[0] For instance, [isAlwaysNull()](https://clang.llvm.org/doxygen/classclang_1_1CXXDynamicCastExpr.html#affd233c7155912b22bb3962a49169f29).

~

[Version 2](https://drive.google.com/file/d/0B3wN6aAcbpi6QW9TWmtLTGJoYVY5T2RnSXZpcnVJR3JhRWYw/view?usp=sharing).

2. The second version is a bit better, as I started to re-implement using the latest C frontend as base, but it doesn't have all the nodes that the first version supported. I was trying to come up with a good solution for the constructor/destructor issue before implementing them all but didn't get very far.

I also tried to address the naming problem: Clang can generate names using the `itanium` name mangler, which should fix a number of names clashing. However, every context lookup (I believe the context were renamed to `symbol_table` in CBMC), needs to be changed to look using the base name, as the unique name is mangled.

This version should be the base, in my opinion, as I implemented an important feature: a hook to the pre-processor to add the ESBMC intrinsics to every source code. This is a must as implicit function declaration is forbidden in C++ and we need to be able to use stuff like `__ESBMC_assume`, `__ESBMC_assert`, etc. It's a nice feature that needs to be further explored. 

~

Some additional explanation:

- The `clang-c-frontend` dir contains the C frontend, clang headers and the pre-processor hook.
- The `clang-cpp-frontend` dir contains the C++ frontend.

The C++ frontend builds on top of the C frontend, so you'll need both.

We ship most of the clang headers with ESBMC (except for the cuda and sanitizer headers), and during the verification they're dumped to `/tmp/` and `-I/tmp/` is added to the clang call. A small improvement would be dumping them to proper temp directory, to avoid including unwanted headers.

The conversion happens in `clang_c_convert*` and it basically creates the ireps. Then it goes through the code in `clang_c_adjust*` to "adjust" the irep to the format the `goto/symex` expects. This is similar to how the old frontend, with the conversion and typecheck/adjustment in separate steps (although we don't need to do any typecheck using clang).

One last thing is that, by using clang, CBMC will lose some of its Predefined Types and Symbols, e.g.:
```c
__CPROVER_bitvector [2] foo;
__CPROVER_floatbv [3] [2] bar;
```
won't work as this is not standard C.

We can work around the issue by annotating the declarations. We do that already for infinite sized arrays:
```c
__attribute__((annotate("__ESBMC_inf_size")))
_Bool foo[1];
```
and the handling the annotation in `clang_c_convertert::get_var`. Something similar can be done for custom bv/fp sizes.

Finally, I have to apologize for the lack of documentation.

----------------------------

I also have to push the latest version of the C++ benchmarks.

**Comment by mikhailramalho** [comment] 2020-06-11 17:53
Some things have changed since I sent this email, in particular:

- All the name resolution should not be a problem anymore since we moved to use clang's Unified Symbol Resolution.
- The custom size for bit-vectors should be implemented when clang is released with _ExtInt.

As I said before: the first task is to rebase the `clang-c-frontend`, and include the basic c++ test in `regression/llvm`. The code there should be similar to the one in Version 2.

After that, it's a matter of listing the clang nodes that we want to implement in ESBMC and implement them.

**Comment by mikhailramalho** [comment] 2020-06-14 23:14
I've created the `clang-cpp-frontend`, which is the code in `clang-c-frontend` rebased on our current master.

We are able to verify several small C++ programs, but only if we are not dealing with objects. Function templates work fine, so programs like:
```
template<class T>
T maximum(T a, T b, T c) {
  T max = a > b? a : b;
  return max > c? max : c;
}

int main() {
  assert(maximum(1, 2, 3) == 3);
  assert(maximum<float>(3.0f, 2.0f, 1.0f) == 2.0f);
  return 0;
}
```
can be correctly verified.

I just realized that it will be a huge pain to review a full frontend, so my suggestion is:
1. Add test cases to the features supported in the current `clang-cpp-frontend` branch and merge it to master.
2. Fix the old cpp frontend so we can compare ireps when adding new features.
3. Create smaller PRs for new supported C++ features.

**Comment by mikhailramalho** [comment] 2020-06-15 00:37
Looks like the reason why esbmc is stuck is related to the cmake build; it is also happening in the old C frontend.

I found at least one missing dependency there: the cpp flex/bison parser depends on the ansi-c one, and there is no clear relation between them. 

I also noticed that there is not clear inclusion of the generated parser in the build, some references mention variables `${FLEX_LIBRARIES} ${BISON_LIBRARIES}` and some others:

https://stackoverflow.com/questions/2491421/cmake-command-syntax-question
https://stackoverflow.com/questions/50827935/how-to-write-a-working-cmake-file-for-flex-bison

So I believe that the parser is not actually being called. @rafaelsamenezes could you check it?

**Comment by rafaelsamenezes** [comment] 2020-06-17 20:12
> I also noticed that there is not clear inclusion of the generated parser in the build, some references mention variables `${FLEX_LIBRARIES} ${BISON_LIBRARIES}` and some others:

You mean the `scanner` and `parser`? They are used into [ansic_with_register](https://github.com/esbmc/esbmc/blob/master/src/ansi-c/CMakeLists.txt#L11)

> So I believe that the parser is not actually being called. @rafaelsamenezes could you check it?

It is called.

> Looks like the reason why esbmc is stuck is related to the cmake build; it is also happening in the old C frontend.

It seems that a `gets`call during `YYINPUT` in the scannerr is hanging forever

**Comment by kunjsong01** [comment] 2023-07-25 13:15
@lucasccordeiro shall we close this issue? The question has been answered, as we've got a pretty clear picture in https://github.com/esbmc/esbmc/wiki/ESBMC-Cpp-Support and https://github.com/esbmc/esbmc/wiki/OM-Workload-Estimate-and-Tracking

**Comment by lucasccordeiro** [comment] 2023-07-25 13:52
Yes! We can close this issue.

**Closed as completed by lucasccordeiro** 2023-07-25 13:52 UTC
Labels: question, C++
