### ISSUE TITLE
[C++ verification] function call: not enough arguments

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#1006] opened 2023-05-05 14:01 UTC
command: `esbmc main.cpp`

```
struct uint3
  {
    unsigned int x, y, z;
  };

uint3 indexOfThread[1024];

int main()
{
    return 0;
}
```

ESBMC version: 92d90b6e3d9ee16eabcd4ce44982a1256afe8492

```
Building error trace

Counterexample:

State 1  thread 0
----------------------------------------------------
Violated property:

  function call: not enough arguments


VERIFICATION FAILED
```
This is the wrong location: `uint3 indexOfThread[1024];`

**Comment by kunjsong01** [comment] 2023-05-05 14:23
Updated the title as this is not a C++-specific problem.

**Comment by kunjsong01** [comment] 2023-05-05 14:29
@XLiZHI 
please could you try it again with`main.cpp` changed to `main.c`?

**Comment by XLiZHI** [comment] 2023-05-05 14:39
> @XLiZHI please could you try it again with`main.cpp` changed to `main.c`?

Hi @kunjsong01 ,
Thanks for your reply.
Yes, I tried the following code in `main.c` and it worked.

```
struct uint3
  {
    unsigned int x, y, z;
  };

struct uint3 indexOfThread[1024];

int main()
{
    return 0;
}
```
The OM I want to verify is in C++-frontend, I tried the following code in `main.cpp`, but still error:
```
extern "C"
{
struct uint3
  {
    unsigned int x, y, z;
  };

struct uint3 indexOfThread[1024];
}

int main()
{
    return 0;
}
```

**Comment by kunjsong01** [comment] 2023-05-05 14:41
>Yes, I tried the following code in main.c and it worked.

Thanks for the confirmation. 
(restored title with [C++ verification] tag as it appears a C++-specific problem)

**Comment by kunjsong01** [comment] 2023-05-05 16:12
Root cause: 
cpp-frontend: 
```
        // 35 
        FUNCTION_CALL:  indexOfThread=uint3() <--- it's calling the constructor without an argument for implicit `this`
```

c-frontend: 
```
        // 34 file tc_1006.c line 6
        indexOfThread=ARRAY_OF({ .x=0, .y=0, .z=0 });
```

**Comment by XLiZHI** [comment] 2023-05-18 09:15
```
(gdb) p expr.dump()
sideeffect
  * type: array
      * size: constant
          * type: signedbv
              * width: 32
          * value: 00000000000000000000010000000000
          * #cformat: 1024
      * subtype: struct
          * tag: uint3
          * components: 
            0: component
                * type: unsignedbv
                    * width: 32
                    * #cpp_type: unsigned_int
                    * #member_name: tag-uint3
                * name: x
                * access: public
                * pretty_name: x
                * #location: 
                  * file: main.cpp
                  * line: 3
            1: component
                * type: unsignedbv
                    * width: 32
                    * #cpp_type: unsigned_int
                    * #member_name: tag-uint3
                * name: y
                * access: public
                * pretty_name: y
                * #location: 
                  * file: main.cpp
                  * line: 3
            2: component
                * type: unsignedbv
                    * width: 32
                    * #cpp_type: unsigned_int
                    * #member_name: tag-uint3
                * name: z
                * access: public
                * pretty_name: z
                * #location: 
                  * file: main.cpp
                  * line: 3
          * methods: 
            0: code
                * type: code
                    * arguments: 
                      0: argument
                          * type: pointer
                              * subtype: symbol
                                  * identifier: tag-uint3
                          * #base_name: this
                          * #identifier: c:@S@uint3@F@uint3#this
                    * return_type: constructor
                    * #inlined: 1
                    * #member_name: tag-uint3
                * name: c:@S@uint3@F@uint3#
                * access: public
                * base_name: c:@S@uint3@F@uint3#
                * pretty_name: uint3
                * is_inlined: 1
                * #location: 
                  * file: main.cpp
                  * line: 1
            1: code
                * type: code
                    * arguments: 
                      0: argument
                          * type: pointer
                              * subtype: symbol
                                  * identifier: tag-uint3
                          * #base_name: this
                          * #identifier: c:@S@uint3@F@uint3#&1$@S@uint3#this
                      1: argument
                          * type: pointer
                              * subtype: symbol
                                  * identifier: tag-uint3
                                  * #constant: 1
                              * #reference: 1
                          * #location: 
                            * file: main.cpp
                            * line: 1
                            * function: uint3
                          * #base_name: ref
                          * #identifier: c:@S@uint3@F@uint3#&1$@S@uint3#::ref
                    * return_type: constructor
                        * #default_copy_cons: 1
                    * #inlined: 1
                    * #member_name: tag-uint3
                * name: c:@S@uint3@F@uint3#&1$@S@uint3#
                * access: public
                * base_name: c:@S@uint3@F@uint3#&1$@S@uint3#
                * pretty_name: uint3
                * is_inlined: 1
                * #location: 
                  * file: main.cpp
                  * line: 1
            2: code
                * type: code
                    * arguments: 
                      0: argument
                          * type: pointer
                              * subtype: symbol
                                  * identifier: tag-uint3
                          * #base_name: this
                          * #identifier: c:@S@uint3@F@~uint3#this
                    * return_type: destructor
                    * #inlined: 1
                    * #member_name: tag-uint3
                * name: c:@S@uint3@F@~uint3#
                * access: public
                * base_name: c:@S@uint3@F@~uint3#
                * pretty_name: ~uint3
                * is_inlined: 1
                * #location: 
                  * file: main.cpp
                  * line: 1
          * #location: 
            * file: main.cpp
            * line: 1
  * operands: 
    0: symbol
        * type: code
            * arguments: 
              * ellipsis: 1
              0: argument
                  * type: pointer
                      * subtype: symbol
                          * identifier: tag-uint3
                  * #base_name: this
                  * #identifier: c:@S@uint3@F@uint3#this
            * return_type: constructor
        * name: uint3
        * identifier: c:@S@uint3@F@uint3#
        * #lvalue: 1
    1: arguments     <-----------------------------This is most likely the cause of no enough arguments
  * statement: function_call
  * constructor: 1
  * #location: 
    * file: main.cpp
    * line: 6
$3 = void
```

**Comment by lucasccordeiro** [comment] 2023-05-25 18:06
Closed via https://github.com/esbmc/esbmc/pull/1040.

**Closed as completed by lucasccordeiro** 2023-05-25 18:06 UTC
Labels: good first issue, C++
