### ISSUE TITLE
ESBMC doesn't detect overflow for signed char

### ISSUE THREAD

**Issue by correcthorsebatterystaple** [esbmc/esbmc#778] opened 2022-06-29 23:33 UTC
Steps to reproduce: Run the following C source with esbmc with the `--overflow-check` option
```c
int main() {
  char i = 127;
  i = i + 1;
}
```

Expected: Verification failed
Actual: Verification successful

After further investigation it is noted that if the assignment is changed to `i++` or `++i` then the overflow is detected and verification, rightfully, fails.

**Comment by correcthorsebatterystaple** [comment] 2022-06-30 00:19
Please ignore the issue ref from the PR above, it has been made by mistake and currently github doesn't let you amend mention histories.

**Comment by lucasccordeiro** [comment] 2022-06-30 03:44
> After further investigation it is noted that if the assignment is changed to i++ or ++i then the overflow is detected and verification, rightfully, fails.

It seems to be an instrumentation bug in goto_check.cpp. Did you check whether the assertion is correctly added?

**Comment by fbrausse** [comment] 2022-06-30 06:23
This is working as intended. It's the integer promotion rules of C. See how `+` is done on type `int` and therefore does not overflow. Output of `esbmc --parse-tree-only`:

![image](https://user-images.githubusercontent.com/3314468/176605503-cd307367-a2cc-47e8-a513-325d193f20b9.png)

The cast back to `char` according to C is "implementation defined" (not undefined), see [C11 6.3.1.3/3](http://port70.net/~nsz/c/c11/n1570.html#6.3.1.3p3).

When you do `i++` or `++i`, indeed arithmetic on `char` is performed and an (undefined) overflow happens.

**Comment by fbrausse** [comment] 2022-07-09 16:17
>> Expected: Verification failed
Actual: Verification successful

> This is working as intended.

@correcthorsebatterystaple Could you please clarify what seems to be the issue here?

**Comment by fbrausse** [comment] 2024-04-16 21:32
Closing as invalid.

**Closed as not planned** 2024-04-16 21:33 UTC
Labels: needs info
