### ISSUE TITLE
ESBMC crashes: [boolector] boolector_write: index bit-width of 'e_array' and bit-width of 'e_index' must be equal

### ISSUE THREAD

**Issue by tihanyin** [esbmc/esbmc#1091] opened 2023-06-15 12:34 UTC
For the following small C program ESBMC 7.2 crashes:

```c
//FormAI DATASET v0.1 Category: File Encyptor ; Style: Claude Shannon
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void encrypt(char* filename, char* key) {
    FILE* file = fopen(filename, "r");
    if (file == NULL) {
        printf("Failed to open file: %s\n", filename);
        return;
    }

    char* encrypted_filename = malloc(strlen(filename) + 4);
    strcpy(encrypted_filename, filename);
    strcat(encrypted_filename, ".enc");

    FILE* encrypted_file = fopen(encrypted_filename, "w");
    if (encrypted_file == NULL) {
        printf("Failed to create encrypted file: %s\n", encrypted_filename);
        fclose(file);
        free(encrypted_filename);
        return;
    }

    int key_len = strlen(key);

    char c = fgetc(file);
    int i = 0;
    while (c != EOF) {
        fputc(c ^ key[i % key_len], encrypted_file);
        c = fgetc(file);
        i++;
    }

    fclose(file);
    fclose(encrypted_file);
    free(encrypted_filename);
}

void decrypt(char* filename, char* key) {
    FILE* encrypted_file = fopen(filename, "r");
    if (encrypted_file == NULL) {
        printf("Failed to open encrypted file: %s\n", filename);
        return;
    }

    char* decrypted_filename = malloc(strlen(filename) - 4);
    strncpy(decrypted_filename, filename, strlen(filename) - 4);

    FILE* decrypted_file = fopen(decrypted_filename, "w");
    if (decrypted_file == NULL) {
        printf("Failed to create decrypted file: %s\n", decrypted_filename);
        fclose(encrypted_file);
        free(decrypted_filename);
        return;
    }

    int key_len = strlen(key);

    char c = fgetc(encrypted_file);
    int i = 0;
    while (c != EOF) {
        fputc(c ^ key[i % key_len], decrypted_file);
        c = fgetc(encrypted_file);
        i++;
    }

    fclose(encrypted_file);
    fclose(decrypted_file);
    free(decrypted_filename);
}

int main() {
    printf("Enter the filename to encrypt: ");
    char filename[256];
    scanf("%s", filename);

    printf("Enter the encryption key: ");
    char key[256];
    scanf("%s", key);

    encrypt(filename, key);
    printf("File encrypted successfully.\n");

    printf("Enter the filename to decrypt: ");
    char encrypted_filename[256];
    scanf("%s", encrypted_filename);

    printf("Enter the decryption key: ");
    char decryption_key[256];
    scanf("%s", decryption_key);

    decrypt(encrypted_filename, decryption_key);
    printf("File decrypted successfully.\n");
    
    return 0;
}
```

ESBMC outptu:

```

esbmc DATA9/FormAI_92515.c --unwind 1
ESBMC version 7.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.126s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
no body for function fputc
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Symex completed in: 0.006s (221 assignments)
Slicing time: 0.000s (removed 93 assignments)
Generated 59 VCC(s), 45 remaining after simplification (128 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
ERROR: Boolector error encountered
[boolector] boolector_write: index bit-width of 'e_array' and bit-width of 'e_index' must be equal

Aborted (core dumped)

```

**Comment by tihanyin** [comment] 2023-06-15 15:44
Maybe is this also fixed by this?https://github.com/esbmc/esbmc/commit/69841f931f3865f6384bb07174be1479987ea057

**Comment by fbrausse** [comment] 2023-06-15 16:14
> Maybe is this also fixed by this?[69841f9](https://github.com/esbmc/esbmc/commit/69841f931f3865f6384bb07174be1479987ea057)

Maybe. If it's not super urgent, I'll check it later. This week is already full with other things.

**Comment by fbrausse** [comment] 2023-06-20 10:52
> Maybe is this also fixed by this?[69841f9](https://github.com/esbmc/esbmc/commit/69841f931f3865f6384bb07174be1479987ea057)

Not quite, but with together with [another fix](https://github.com/fbrausse/esbmc/commit/385c2f091673df69b59a681ba9157700398a20a1) in #905 the problem is solved.

**Comment by lucasccordeiro** [comment] 2023-06-20 10:55
@fbrausse: Excellent ;-) when could we get https://github.com/esbmc/esbmc/pull/905 into the master? :-)

**Comment by fbrausse** [comment] 2023-06-20 10:58
> @fbrausse: Excellent ;-) when could we get #905 into the master? :-)

Thanks! I'm working on resolving the conflicts with the master branch right now.

**Comment by lucasccordeiro** [comment] 2023-06-20 12:32
Excellent, @fbrausse

**Closed as completed** 2023-07-09 14:30 UTC
